WIP: Add Envoy Skycfg Example
stripe/skycfg pull request #82
Opened 2020-09-28 21:12 UTC by idiamond-stripe

This PR adds a very simple Skcyfg example that runs an Envoy xDS using https://github.com/envoyproxy/go-control-plane. The example loads the provided config on start, and reloads the config on `SIGHUP`.

2020-09-29 02:11 UTC, jmillikin-stripe requested changes
General comment: It might be better to separate the skycfg changes (such as `google.protobuf.Any` support) into a separate PR, since they are not Envoy-specific functionality.

For the Envoy parts: would it be possible to simplify the example? For example by converting it to a plain front-proxy of `http://example.com`

2020-09-29 02:11 UTC, jmillikin-stripe commented on internal/go/skycfg/proto_api.go
> +			"to_proto":     starlark.NewBuiltin("proto.to_proto", fnProtoToProto),
Let's add functions like `to_any`, which return the `google.protobuf.Any` directly. This way users don't have to deal with the internal details of the type URLs, and don't need to define their own marshal/unmarshal helpers.

2020-09-29 02:11 UTC, jmillikin-stripe commented on internal/go/skycfg/proto_api.go
> +			"name":        starlark.NewBuiltin("proto.clone", fnProtoName),
I believe this functionality is already available via `type(msg)`.

2020-09-29 02:11 UTC, jmillikin-stripe commented on go.mod
> +	github.com/envoyproxy/go-control-plane v0.9.6 // indirect
It looks like something in your dev environment got confused about which `go.mod` to update. It also touched a bunch of files in the other examples. Can you revert these unrelated changes?

2020-09-30 05:30 UTC, idiamond-stripe commented
I've removed the `any` changes and landed them here: https://github.com/stripe/skycfg/pull/83.

I've also simplified the example to run on two ports (`10000` and `10001`) and proxied them to example.com and example.org respectively.

All the other changes from the first, in progress review here are minor. I've added a health check and improved some go modules by `go mod tidy`, but overall these are mainly cosmetic. I should probably document the way this example works, but can do so in a follow up PR.

2020-10-01 03:59 UTC, jmillikin-stripe approved these changes
LGTM

2020-10-01 04:01 UTC, merged