Simplify tests with runSkycfgTests test runner
stripe/skycfg pull request #98
Opened 2021-08-31 22:12 UTC by seena-stripe

## Summary
Adds a test runner `runSkycfgTests` to remove redundant testing logic. Many of the tests had a 1 line skycfg expression and a 1 line desired output, but duplicated all the test boilerplate, so this PR adds a test runner to simplify setting up a new test

This is purely cleanup and shouldn't affect evaluation.

Example
```diff
 func TestUnsetProto2Fields(t *testing.T) {
        // Proto v2 distinguishes between unset and set-to-empty.
-       msg, err := eval(`proto.package("skycfg.test_proto").MessageV2(
-                f_string = None,
-        )`, nil)
-       if err != nil {
-               t.Fatal(err)
-       }
-       got := mustProtoMessage(t, msg)
-       want := &pb.MessageV2{
-               FString: nil,
-       }
-       checkProtoEqual(t, want, got)
+       runSkycfgTests(t, []skycfgTest{
+               {
+                       src: `proto.package("skycfg.test_proto").MessageV2(
+                               f_string = None,
+                       )`,
+                       want: &pb.MessageV2{
+                               FString: nil,
+                       },
+               },
+       })
 }
```

This doesn't save on LoC very much but reduces the boilerplate so the test code is a lot more signalful and test output is consistent

2021-09-07 22:04 UTC, kathleen-stripe requested changes
Only the `want != nil && got == nil` change is blocking. Thanks for doing this refactor!

2021-09-07 22:04 UTC, kathleen-stripe commented on go/protomodule/protomodule_message_test.go
> +	runSkycfgTests(t, []skycfgTest{
nit: This function invocation might be easier to read if the `[]skycfgTest` slice was extracted into a variable and the variable was passed to `runSkycfgTests` instead.

2021-09-07 22:04 UTC, kathleen-stripe commented on go/protomodule/protomodule_test.go
> +					t.Fatalf("Expected\nwanted: %s\ngot   : %s", want, got)
nit: not sure if this error makes sense - could we remove the "Expected" or reword? (same for lines below)

EDIT: Or is "Expected" intended to indicate what expectation failed? e.g. expected value vs expected error?

2021-09-07 22:04 UTC, kathleen-stripe commented on go/protomodule/protomodule_test.go
> +	} else if want != nil && got.Error() != want.Error() {
It seems like we also need to handle `want != nil && got == nil`, right?

2021-09-08 17:58 UTC, seena-stripe commented on go/protomodule/protomodule_test.go
> +					t.Fatalf("Expected\nwanted: %s\ngot   : %s", want, got)
Yeah it was intended to be "Value received differed from expected" or something similar, but I'm not sure how to word it best and it's not providing much value over `wanted: foo, got: bar` so I'm just removing it

2021-09-08 17:59 UTC, seena-stripe commented on go/protomodule/protomodule_test.go
> +	} else if want != nil && got.Error() != want.Error() {
Oh yeah, great catch

2021-09-08 18:10 UTC, kathleen-stripe approved these changes

2021-09-08 18:29 UTC, merged